Repository 2019-2-arquitetura-desenho/monitoria-api, pull requests merged in 2019-11, with the labels that each got.

#41 Bugfix/pdf reader
  pdf_reader/LeitorPDF.py
Labels: Hotfix, Importante, Inscrição, bug

#39 Fixing registration request
  pdf_reader/LeitorPDF.py
  profiles/views.py
Labels: Hotfix

#35 BugFix - Sincronização de serviços em Containeres
  Dockerfile
  docker-compose.yml
  entrypoint.sh
  wait-for-postgres.py
Labels: Ambiente, Hotfix, bug

#38 Connecting student subject code with crawler subjects
  env-reference
  monitoria/settings.py
  profiles/urls.py
  profiles/views.py
Labels: Funcionalidade, Importante, Perfis
