Repository 2019-2-arquitetura-desenho/monitoria-api, pull requests merged in 2019-10, with the labels that each got.

#15 Adding password reset
  monitoria/urls.py
Labels: Funcionalidade, Perfis

#17 Changing default reset password email
  monitoria/settings.py
  templates/registration/password_reset_email.html
  templates/registration/password_reset_subject.txt
Labels: Perfis

#14 Perfil Estudante
  monitoria/auth_urls.py
  monitoria/settings.py
  monitoria/urls.py
  profiles/__init__.py
  profiles/admin.py
  profiles/apps.py
  profiles/migrations/0001_initial.py
  profiles/migrations/0002_auto_20191011_1209.py
  profiles/migrations/0003_auto_20191011_1212.py
  profiles/migrations/0004_auto_20191011_1259.py
  profiles/migrations/__init__.py
  profiles/models.py
  profiles/serializers.py
  profiles/test_data.json
  profiles/tests.py
  profiles/urls.py
  profiles/validators.py
  profiles/views.py
Labels: Funcionalidade, Perfis

#19 Feature/password reset
  monitoria/settings.py
  static/images/logo_full.png
  templates/registration/logo_full.png
  templates/registration/password_reset_complete.html
  templates/registration/password_reset_confirm.html
  templates/registration/password_reset_done.html
  templates/registration/password_reset_form.html
Labels: Funcionalidade, Perfis

#21 Bug/env
  env-reference
  monitoria/context_processors.py
  monitoria/settings.py
  monitoria/templatetags/__init__.py
  monitoria/templatetags/poll_extras.py
  monitoria/urls.py
  requirements.txt
  templates/registration/logo_full.png
  templates/registration/password_reset_complete.html
  templates/registration/password_reset_email.html
  templates/registration/password_reset_form.html
Labels: Ambiente, bug

#23 Correção do bug de registro
  profiles/views.py
Labels: bug

#25 Feature/email and env
  .gitignore
  env-reference
  monitoria/settings.py
  requirements.txt
  templates/registration/password_reset_complete.html
  templates/registration/password_reset_confirm.html
  templates/registration/password_reset_done.html
  templates/registration/password_reset_form.html
Labels: Funcionalidade, Perfis
